陽性患者の属性を公表日順に並べ替え
Stop-COVID19-Nagano/covid19 pull request #80
Opened 2020-04-06 01:14 UTC by ShinoharaTa

#79 の対応です。公表日順に並べ替えました。

![image](https://user-images.githubusercontent.com/23314412/78515052-61356600-77ef-11ea-8740-e00a22232014.png)

2020-04-06 03:26 UTC, ShinoharaTa commented
こちら、i18nの追加対応が必要になりました。
warning取れるまでもう少々かかります。これから対応します。

2020-04-06 06:54 UTC, ShinoharaTa commented
対応完了です

2020-04-06 09:32 UTC, kikd requested changes
レビューでコメントを入れたので確認をお願いします。

また、次からで良いのですが、1つのプルリクエストに含めるissueは1つにとどめていただけるとレビューしやすいです。

2020-04-06 09:32 UTC, kikd commented on utils/colors.ts
> +}
チャートのスタイル追従についてはissueが発行されていない気がします。
こちらについては別途issueとPRを発行いただけますでしょうか。

2020-04-06 09:36 UTC, ShinoharaTa commented on utils/colors.ts
> +}
かしこまりました。一回追加したカードのデザインはもとに戻して再度発行します

2020-04-06 09:37 UTC, kikd commented
ワークフローに変更入っていますので認証情報などお気をつけください！

2020-04-06 15:55 UTC, ShinoharaTa commented
対応しました。
合わせて、最新のdev環境をマージしています。

2020-04-07 01:55 UTC, kikd approved these changes
対応ありがとうございました。

2020-04-07 01:55 UTC, merged